INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('1.8.0','Positive active energy total','Positive active energy (A+) total [kWh]',false,false),
	 ('1.8.1','Positive active energy in tariff T1','Positive active energy (A+) in tariff T1 [kWh]',false,false),
	 ('1.8.2','Positive active energy in tariff T2','Positive active energy (A+) in tariff T2 [kWh]',false,false),
	 ('1.8.3','Positive active energy in tariff T3','Positive active energy (A+) in tariff T3 [kWh]',false,false),
	 ('1.8.4','Positive active energy in tariff T4','Positive active energy (A+) in tariff T4 [kWh]',false,false),
	 ('2.8.0','Negative active energy total','Negative active energy (A+) total [kWh]',false,false),
	 ('2.8.1','Negative active energy in tariff T1','Negative active energy (A+) in tariff T1 [kWh]',false,false),
	 ('2.8.2','Negative active energy in tariff T2','Negative active energy (A+) in tariff T2 [kWh]',false,false),
	 ('2.8.3','Negative active energy in tariff T3','Negative active energy (A+) in tariff T3 [kWh]',false,false),
	 ('2.8.4','Negative active energy in tariff T4','Negative active energy (A+) in tariff T4 [kWh]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('15.8.0','Absolute active energy total','Absolute active energy (A+) total [kWh]',false,false),
	 ('15.8.1','Absolute active energy in tariff T1','Absolute active energy (A+) in tariff T1 [kWh]',false,false),
	 ('15.8.2','Absolute active energy in tariff T2','Absolute active energy (A+) in tariff T2 [kWh]',false,false),
	 ('15.8.3','Absolute active energy in tariff T3','Absolute active energy (A+) in tariff T3 [kWh]',false,false),
	 ('15.8.4','Absolute active energy in tariff T4','Absolute active energy (A+) in tariff T4 [kWh]',false,false),
	 ('16.8.0','Sum active energy without reverse blockade total','Sum active energy without reverse blockade (A+ - A-) total [kWh]',false,false),
	 ('16.8.1','Sum active energy without reverse blockade in tariff T1','Sum active energy without reverse blockade (A+ - A-) in tariff T1 [kWh]',false,false),
	 ('16.8.2','Sum active energy without reverse blockade in tariff T2','Sum active energy without reverse blockade (A+ - A-) in tariff T2 [kWh]',false,false),
	 ('16.8.3','Sum active energy without reverse blockade in tariff T3','Sum active energy without reverse blockade (A+ - A-) in tariff T3 [kWh]',false,false),
	 ('16.8.4','Sum active energy without reverse blockade in tariff T4','Sum active energy without reverse blockade (A+ - A-) in tariff T4 [kWh]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('3.8.0','Positive reactive energy total','Positive reactive energy (Q+) total [kvarh]',false,false),
	 ('3.8.1','Positive reactive energy in tariff T1','Positive reactive energy (Q+) in tariff T1 [kvarh]',false,false),
	 ('3.8.2','Positive reactive energy in tariff T2','Positive reactive energy (Q+) in tariff T2 [kvarh]',false,false),
	 ('3.8.3','Positive reactive energy in tariff T3','Positive reactive energy (Q+) in tariff T3 [kvarh]',false,false),
	 ('3.8.4','Positive reactive energy in tariff T4','Positive reactive energy (Q+) in tariff T4 [kvarh]',false,false),
	 ('4.8.0','Negative reactive energy total','Negative reactive energy (Q-) total [kvarh]',false,false),
	 ('4.8.1','Negative reactive energy in tariff T1','Negative reactive energy (Q-) in tariff T1 [kvarh]',false,false),
	 ('4.8.2','Negative reactive energy in tariff T2','Negative reactive energy (Q-) in tariff T2 [kvarh]',false,false),
	 ('4.8.3','Negative reactive energy in tariff T3','Negative reactive energy (Q-) in tariff T3 [kvarh]',false,false),
	 ('4.8.4','Negative reactive energy in tariff T4','Negative reactive energy (Q-) in tariff T4 [kvarh]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('5.8.0','Imported inductive reactive energy in 1-st quadrant total','Imported inductive reactive energy in 1-st quadrant (Q1) total [kvarh]',false,false),
	 ('5.8.1','Imported inductive reactive energy in 1-st quadrant in tariff T1','Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T1 [kvarh]',false,false),
	 ('5.8.2','Imported inductive reactive energy in 1-st quadrant in tariff T2','Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T2 [kvarh]',false,false),
	 ('5.8.3','Imported inductive reactive energy in 1-st quadrant in tariff T3','Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T3 [kvarh]',false,false),
	 ('5.8.4','Imported inductive reactive energy in 1-st quadrant in tariff T4','Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T4 [kvarh]',false,false),
	 ('6.8.0','Imported capacitive reactive energy in 2-nd quadrant total','Imported capacitive reactive energy in 2-nd quadrant (Q2) total [kvarh]',false,false),
	 ('6.8.1','Imported capacitive reactive energy in 2-nd quadr. in tariff T1','Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T1 [kvarh]',false,false),
	 ('6.8.2','Imported capacitive reactive energy in 2-nd quadr. in tariff T2','Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T2 [kvarh]',false,false),
	 ('6.8.3','Imported capacitive reactive energy in 2-nd quadr. in tariff T3','Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T3 [kvarh]',false,false),
	 ('6.8.4','Imported capacitive reactive energy in 2-nd quadr. in tariff T4','Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T4 [kvarh]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('7.8.0','Exported inductive reactive energy in 3-rd quadrant total','Exported inductive reactive energy in 3-rd quadrant (Q3) total [kvarh]',false,false),
	 ('7.8.1','Exported inductive reactive energy in 3-rd quadrant in tariff T1','Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T1 [kvarh]',false,false),
	 ('7.8.2','Exported inductive reactive energy in 3-rd quadrant in tariff T2','Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T2 [kvarh]',false,false),
	 ('7.8.3','Exported inductive reactive energy in 3-rd quadrant in tariff T3','Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T3 [kvarh]',false,false),
	 ('7.8.4','Exported inductive reactive energy in 3-rd quadrant in tariff T4','Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T4 [kvarh]',false,false),
	 ('8.8.0','Exported capacitive reactive energy in 4-th quadrant total','Exported capacitive reactive energy in 4-th quadrant (Q4) total [kvarh]',false,false),
	 ('8.8.1','Exported capacitive reactive energy in 4-th quadr. in tariff T1','Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T1 [kvarh]',false,false),
	 ('8.8.2','Exported capacitive reactive energy in 4-th quadr. in tariff T2','Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T2 [kvarh]',false,false),
	 ('8.8.3','Exported capacitive reactive energy in 4-th quadr. in tariff T3','Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T3 [kvarh]',false,false),
	 ('8.8.4','Exported capacitive reactive energy in 4-th quadr. in tariff T4','Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T4 [kvarh]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('9.8.0','Apparent energy total','Apparent energy (S+) total [kVAh]',false,false),
	 ('9.8.1','Apparent energy in tariff T1','Apparent energy (S+) in tariff T1 [kVAh]',false,false),
	 ('9.8.2','Apparent energy in tariff T2','Apparent energy (S+) in tariff T2 [kVAh]',false,false),
	 ('9.8.3','Apparent energy in tariff T3','Apparent energy (S+) in tariff T3 [kVAh]',false,false),
	 ('9.8.4','Apparent energy in tariff T4','Apparent energy (S+) in tariff T4 [kVAh]',false,false),
	 ('21.8.0','Positive active energy in phase L1 total','Positive active energy (A+) in phase L1 total [kWh]',false,false),
	 ('41.8.0','Positive active energy in phase L2 total','Positive active energy (A+) in phase L2 total [kWh]',false,false),
	 ('61.8.0','Positive active energy in phase L3 total','Positive active energy (A+) in phase L3 total [kWh]',false,false),
	 ('22.8.0','Negative active energy in phase L1 total','Negative active energy (A-) in phase L1 total [kWh]',false,false),
	 ('42.8.0','Negative active energy in phase L2 total','Negative active energy (A-) in phase L2 total [kWh]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('62.8.0','Negative active energy in phase L3 total','Negative active energy (A-) in phase L3 total [kWh]',false,false),
	 ('35.8.0','Absolute active energy in phase L1 total','Absolute active energy (|A|) in phase L1 total [kWh]',false,false),
	 ('55.8.0','Absolute active energy in phase L2 total','Absolute active energy (|A|) in phase L2 total [kWh]',false,false),
	 ('75.8.0','Absolute active energy in phase L3 total','Absolute active energy (|A|) in phase L3 total [kWh]',false,false),
	 ('1.6.0','Positive active maximum demand total','Positive active maximum demand (A+) total [kW]',false,false),
	 ('1.6.1','Positive active maximum demand in tariff T1','Positive active maximum demand (A+) in tariff T1 [kW]',false,false),
	 ('1.6.2','Positive active maximum demand in tariff T2','Positive active maximum demand (A+) in tariff T2 [kW]',false,false),
	 ('1.6.3','Positive active maximum demand in tariff T3','Positive active maximum demand (A+) in tariff T3 [kW]',false,false),
	 ('1.6.4','Positive active maximum demand in tariff T4','Positive active maximum demand (A+) in tariff T4 [kW]',false,false),
	 ('2.6.0','Negative active maximum demand total','Negative active maximum demand (A-) total [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('2.6.1','Negative active maximum demand in tariff T1','Negative active maximum demand (A-) in tariff T1 [kW]',false,false),
	 ('2.6.2','Negative active maximum demand in tariff T2','Negative active maximum demand (A-) in tariff T2 [kW]',false,false),
	 ('2.6.3','Negative active maximum demand in tariff T3','Negative active maximum demand (A-) in tariff T3 [kW]',false,false),
	 ('2.6.4','Negative active maximum demand in tariff T4','Negative active maximum demand (A-) in tariff T4 [kW]',false,false),
	 ('15.6.0','Absolute active maximum demand total','Absolute active maximum demand (|A|) total [kW]',false,false),
	 ('15.6.1','Absolute active maximum demand in tariff T1','Absolute active maximum demand (|A|) in tariff T1 [kW]',false,false),
	 ('15.6.2','Absolute active maximum demand in tariff T2','Absolute active maximum demand (|A|) in tariff T2 [kW]',false,false),
	 ('15.6.3','Absolute active maximum demand in tariff T3','Absolute active maximum demand (|A|) in tariff T3 [kW]',false,false),
	 ('15.6.4','Absolute active maximum demand in tariff T4','Absolute active maximum demand (|A|) in tariff T4 [kW]',false,false),
	 ('3.6.0','Positive reactive maximum demand total','Positive reactive maximum demand (Q+) total [kvar]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('4.6.0','Negative reactive maximum demand total','Negative reactive maximum demand (Q-) total [kvar]',false,false),
	 ('5.6.0','Reactive maximum demand in Q1 total','Reactive maximum demand in Q1 (Q1) total [kvar]',false,false),
	 ('6.6.0','Reactive maximum demand in Q2 total','Reactive maximum demand in Q2 (Q2) total [kvar]',false,false),
	 ('7.6.0','Reactive maximum demand in Q3 total','Reactive maximum demand in Q3 (Q3) total [kvar]',false,false),
	 ('8.6.0','Reactive maximum demand in Q4 total','Reactive maximum demand in Q4 (Q4) total [kvar]',false,false),
	 ('9.6.0','Apparent maximum demand total','Apparent maximum demand (S+) total [kVA]',false,false),
	 ('1.2.0','Positive active cumulative maximum demand total','Positive active cumulative maximum demand (A+) total [kW]',false,false),
	 ('1.2.1','Positive active cumulative maximum demand in tariff T1','Positive active cumulative maximum demand (A+) in tariff T1 [kW]',false,false),
	 ('1.2.2','Positive active cumulative maximum demand in tariff T2','Positive active cumulative maximum demand (A+) in tariff T2 [kW]',false,false),
	 ('1.2.3','Positive active cumulative maximum demand in tariff T3','Positive active cumulative maximum demand (A+) in tariff T3 [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('1.2.4','Positive active cumulative maximum demand in tariff T4','Positive active cumulative maximum demand (A+) in tariff T4 [kW]',false,false),
	 ('2.2.0','Negative active cumulative maximum demand total','Negative active cumulative maximum demand (A-) total [kW]',false,false),
	 ('2.2.1','Negative active cumulative maximum demand in tariff T1','Negative active cumulative maximum demand (A-) in tariff T1 [kW]',false,false),
	 ('2.2.2','Negative active cumulative maximum demand in tariff T2','Negative active cumulative maximum demand (A-) in tariff T2 [kW]',false,false),
	 ('2.2.3','Negative active cumulative maximum demand in tariff T3','Negative active cumulative maximum demand (A-) in tariff T3 [kW]',false,false),
	 ('2.2.4','Negative active cumulative maximum demand in tariff T4','Negative active cumulative maximum demand (A-) in tariff T4 [kW]',false,false),
	 ('15.2.0','Absolute active cumulative maximum demand total','Absolute active cumulative maximum demand (|A|) total [kW]',false,false),
	 ('15.2.1','Absolute active cumulative maximum demand in tariff T1','Absolute active cumulative maximum demand (|A|) in tariff T1 [kW]',false,false),
	 ('15.2.2','Absolute active cumulative maximum demand in tariff T2','Absolute active cumulative maximum demand (|A|) in tariff T2 [kW]',false,false),
	 ('15.2.3','Absolute active cumulative maximum demand in tariff T3','Absolute active cumulative maximum demand (|A|) in tariff T3 [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('15.2.4','Absolute active cumulative maximum demand in tariff T4','Absolute active cumulative maximum demand (|A|) in tariff T4 [kW]',false,false),
	 ('3.2.0','Positive reactive cumulative maximum demand total','Positive reactive cumulative maximum demand (Q+) total [kvar]',false,false),
	 ('4.2.0','Negative reactive cumulative maximum demand total','Negative reactive cumulative maximum demand (Q-) total [kvar]',false,false),
	 ('5.2.0','Reactive cumulative maximum demand in Q1 total','Reactive cumulative maximum demand in Q1 (Q1) total [kvar]',false,false),
	 ('6.2.0','Reactive cumulative maximum demand in Q2 total','Reactive cumulative maximum demand in Q2 (Q2) total [kvar]',false,false),
	 ('7.2.0','Reactive cumulative maximum demand in Q3 total','Reactive cumulative maximum demand in Q3 (Q3) total [kvar]',false,false),
	 ('8.2.0','Reactive cumulative maximum demand in Q4 total','Reactive cumulative maximum demand in Q4 (Q4) total [kvar]',false,false),
	 ('9.2.0','Apparent cumulative maximum demand total','Apparent cumulative maximum demand (S+) total [kVA]',false,false),
	 ('1.4.0','Positive active demand in current demand period','Positive active demand in a current demand period (A+) [kW]',false,false),
	 ('2.4.0','Negative active demand in current demand period','Negative active demand in a current demand period (A-) [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('C.86.0','Installation check','Installation check',false,false),
	 ('15.4.0','Absolute active demand in current demand period','Absolute active demand in a current demand period (|A|) [kW]',false,false),
	 ('3.4.0','Positive reactive demand in current demand period','Positive reactive demand in a current demand period (Q+) [kvar]',false,false),
	 ('4.4.0','Negative reactive demand in current demand period','Negative reactive demand in a current demand period (Q-) [kvar]',false,false),
	 ('5.4.0','Reactive demand in current demand period in Q1','Reactive demand in a current demand period in Q1 (Q1) [kvar]',false,false),
	 ('6.4.0','Reactive demand in current demand period in Q2','Reactive demand in a current demand period in Q2 (Q2) [kvar]',false,false),
	 ('7.4.0','Reactive demand in current demand period in Q3','Reactive demand in a current demand period in Q3 (Q3) [kvar]',false,false),
	 ('8.4.0','Reactive demand in current demand period in Q4','Reactive demand in a current demand period in Q4 (Q4) [kvar]',false,false),
	 ('9.4.0','Apparent demand in current demand period','Apparent demand in a current demand period (S+) [kVA]',false,false),
	 ('1.5.0','Positive active demand in the last completed demand period','Positive active demand in the last completed demand period (A+) [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('2.5.0','Negative active demand in the last completed demand period','Negative active demand in the last completed demand period (A-) [kW]',false,false),
	 ('15.5.0','Absolute active demand in the last completed demand period','Absolute active demand in the last completed demand period (|A|) [kW]',false,false),
	 ('3.5.0','Positive reactive demand in the last completed demand period','Positive reactive demand in the last completed demand period (Q+) [kvar]',false,false),
	 ('4.5.0','Negative reactive demand in the last completed demand period','Negative reactive demand in the last completed demand period (Q-) [kvar]',false,false),
	 ('5.5.0','Reactive demand in the last completed demand period in Q1','Reactive demand in the last completed demand period in Q1 (Q1) [kvar]',false,false),
	 ('6.5.0','Reactive demand in the last completed demand period in Q2','Reactive demand in the last completed demand period in Q2 (Q2) [kvar]',false,false),
	 ('7.5.0','Reactive demand in the last completed demand period in Q3','Reactive demand in the last completed demand period in Q3 (Q3) [kvar]',false,false),
	 ('8.5.0','Reactive demand in the last completed demand period in Q4','Reactive demand in the last completed demand period in Q4 (Q4) [kvar]',false,false),
	 ('9.5.0','Apparent demand in the last completed demand period','Apparent demand in the last completed demand period (S+) [kVA]',false,false),
	 ('1.7.0','Positive active instantaneous power','Positive active instantaneous power (A+) [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('21.7.0','Positive active instantaneous power in phase L1','Positive active instantaneous power (A+) in phase L1 [kW]',false,false),
	 ('41.7.0','Positive active instantaneous power in phase L2','Positive active instantaneous power (A+) in phase L2 [kW]',false,false),
	 ('61.7.0','Positive active instantaneous power in phase L3','Positive active instantaneous power (A+) in phase L3 [kW]',false,false),
	 ('2.7.0','Negative active instantaneous power','Negative active instantaneous power (A-) [kW]',false,false),
	 ('22.7.0','Negative active instantaneous power in phase L1','Negative active instantaneous power (A-) in phase L1 [kW]',false,false),
	 ('42.7.0','Negative active instantaneous power in phase L2','Negative active instantaneous power (A-) in phase L2 [kW]',false,false),
	 ('62.7.0','Negative active instantaneous power in phase L3','Negative active instantaneous power (A-) in phase L3 [kW]',false,false),
	 ('15.7.0','Absolute active instantaneous power','Absolute active instantaneous power (|A|) [kW]',false,false),
	 ('35.7.0','Absolute active instantaneous power in phase L1','Absolute active instantaneous power (|A|) in phase L1 [kW]',false,false),
	 ('55.7.0','Absolute active instantaneous power in phase L2','Absolute active instantaneous power (|A|) in phase L2 [kW]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('75.7.0','Absolute active instantaneous power in phase L3','Absolute active instantaneous power (|A|) in phase L3 [kW]',false,false),
	 ('16.7.0','Sum active instantaneous power','Sum active instantaneous power (A+ - A-) [kW]',false,false),
	 ('36.7.0','Sum active instantaneous power in phase L1','Sum active instantaneous power (A+ - A-) in phase L1 [kW]',false,false),
	 ('56.7.0','Sum active instantaneous power in phase L2','Sum active instantaneous power (A+ - A-) in phase L2 [kW]',false,false),
	 ('76.7.0','Sum active instantaneous power in phase L3','Sum active instantaneous power (A+ - A-) in phase L3 [kW]',false,false),
	 ('3.7.0','Positive reactive instantaneous power','Positive reactive instantaneous power (Q+) [kvar]',false,false),
	 ('23.7.0','Positive reactive instantaneous power in phase L1','Positive reactive instantaneous power (Q+) in phase L1 [kvar]',false,false),
	 ('43.7.0','Positive reactive instantaneous power in phase L2','Positive reactive instantaneous power (Q+) in phase L2 [kvar]',false,false),
	 ('63.7.0','Positive reactive instantaneous power in phase L3','Positive reactive instantaneous power (Q+) in phase L3 [kvar]',false,false),
	 ('4.7.0','Negative reactive instantaneous power','Negative reactive instantaneous power (Q-) [kvar]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('24.7.0','Negative reactive instantaneous power in phase L1','Negative reactive instantaneous power (Q-) in phase L1 [kvar]',false,false),
	 ('44.7.0','Negative reactive instantaneous power in phase L2','Negative reactive instantaneous power (Q-) in phase L2 [kvar]',false,false),
	 ('64.7.0','Negative reactive instantaneous power in phase L3','Negative reactive instantaneous power (Q-) in phase L3 [kvar]',false,false),
	 ('9.7.0','Apparent instantaneous power','Apparent instantaneous power (S+) [kVA]',false,false),
	 ('29.7.0','Apparent instantaneous power in phase L1','Apparent instantaneous power (S+) in phase L1 [kVA]',false,false),
	 ('49.7.0','Apparent instantaneous power in phase L2','Apparent instantaneous power (S+) in phase L2 [kVA]',false,false),
	 ('69.7.0','Apparent instantaneous power in phase L3','Apparent instantaneous power (S+) in phase L3 [kVA]',false,false),
	 ('11.7.0','Instantaneous current','Instantaneous current (I) [A]',false,false),
	 ('91.7.0','Instantaneous current in neutral','Instantaneous current (I) in neutral [A]',false,false),
	 ('11.6.0','Maximum current','Maximum current (I max) [A]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('31.6.0','Maximum current in phase L1','Maximum current (I max) in phase L1 [A]',false,false),
	 ('51.6.0','Maximum current in phase L2','Maximum current (I max) in phase L2 [A]',false,false),
	 ('71.6.0','Maximum current in phase L3','Maximum current (I max) in phase L3 [A]',false,false),
	 ('91.6.0','Maximum current in neutral','Maximum current (I max) in neutral [A]',false,false),
	 ('12.7.0','Instantaneous voltage','Instantaneous voltage (U) [V]',false,false),
	 ('13.7.0','Instantaneous power factor','Instantaneous power factor',false,false),
	 ('33.7.0','Instantaneous power factor in phase L1','Instantaneous power factor in phase L1',false,false),
	 ('53.7.0','Instantaneous power factor in phase L2','Instantaneous power factor in phase L2',false,false),
	 ('73.7.0','Instantaneous power factor in phase L3','Instantaneous power factor in phase L3',false,false),
	 ('14.7.0','Frequency','Frequency [Hz]',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('C.53.1','Tamper 1 energy register','Tamper 1 energy register',false,false),
	 ('C.53.2','Tamper 2 energy register','Tamper 2 energy register',false,false),
	 ('C.53.3','Tamper 3 energy register','Tamper 3 energy register',false,false),
	 ('C.53.4','Tamper 4 energy register','Tamper 4 energy register',false,false),
	 ('C.53.11','Tamper 5 energy register','Tamper 5 energy register',false,false),
	 ('C.53.5','Tamper 1 time counter register','Tamper 1 time counter register',false,false),
	 ('C.53.6','Tamper 2 time counter register','Tamper 2 time counter register',false,false),
	 ('C.53.7','Tamper 3 time counter register','Tamper 3 time counter register',false,false),
	 ('C.53.9','Tamper 4 time counter register','Tamper 4 time counter register',false,false),
	 ('C.53.10','Tamper 5 time counter register','Tamper 5 time counter register',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('C.2.0','Event parameters change - counter','Event parameters change - counter',false,false),
	 ('C.2.1','Event parameters change - timestamp','Event parameters change - timestamp',false,false),
	 ('C.51.1','Event terminal cover opened - counter','Event terminal cover opened - counter',false,false),
	 ('C.51.2','Event terminal cover opened - timestamp','Event terminal cover opened - timestamp',false,false),
	 ('C.51.3','Event main cover opened - counter','Event main cover opened - counter',false,false),
	 ('C.51.5','Event magnetic field detection start - counter','Event magnetic field detection start - counter',false,false),
	 ('C.51.6','Event magnetic field detection start - timestamp','Event magnetic field detection start - timestamp',false,false),
	 ('C.51.7','Event reverse power flow - counter','Event reverse power flow - counter',false,false),
	 ('C.51.8','Event reverse power flow - timestamp','Event reverse power flow - timestamp',false,false),
	 ('C.7.10','Event power down - timestamp','Event power down - timestamp',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('C.51.13','Event power up - counter','Event power up - counter',false,false),
	 ('C.51.14','Event power up – timestamp','Event power up – timestamp',false,false),
	 ('C.51.15','Event RTC (Real Time Clock) set - counter','Event RTC (Real Time Clock) set - counter',false,false),
	 ('C.51.16','Event RTC (Real Time Clock) set - timestamp','Event RTC (Real Time Clock) set - timestamp',false,false),
	 ('C.51.21','Event terminal cover closed - counter','Event terminal cover closed - counter',false,false),
	 ('C.51.22','Event terminal cover closed - timestamp','Event terminal cover closed - timestamp',false,false),
	 ('C.51.23','Event main cover closed - counter','Event main cover closed - counter',false,false),
	 ('C.51.24','Event main cover closed - timestamp','Event main cover closed - timestamp',false,false),
	 ('C.51.25','Event log-book 1 erased - counter','Event log-book 1 erased - counter',false,false),
	 ('C.51.26','Event log-book 1 erased - timestamp','Event log-book 1 erased - timestamp',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('C.51.27','Event fraud start - counter','Event fraud start - counter',false,false),
	 ('C.51.28','Event fraud start - timestamp','Event fraud start - timestamp',false,false),
	 ('C.51.29','Event fraud stop - counter','Event fraud stop - counter',false,false),
	 ('C.51.30','Event fraud stop - timestamp','Event fraud stop - timestamp',false,false),
	 ('0.9.1','Current time','Current time (hh:mm:ss)',false,false),
	 ('0.9.2','Date','Date (YY.MM.DD or DD.MM.YY)',false,false),
	 ('0.9.4','Date and Time','Date and Time (YYMMDDhhmmss)',false,false),
	 ('0.8.0','Demand period','Demand period [min]',false,false),
	 ('0.8.4','Load profile period','Load profile period [min] (option)',false,false),
	 ('0.0.0','Device address 1','Device address 1',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('0.0.1','Device address 2','Device address 2',false,false),
	 ('0.1.0','MD reset counter','MD reset counter',false,false),
	 ('0.1.2','MD reset timestamp','MD reset timestamp',false,false),
	 ('0.2.0','Firmware version','Firmware version',false,false),
	 ('0.2.2','Tariff program ID','Tariff program ID',false,false),
	 ('C.1.0','Meter serial number','Meter serial number',false,false),
	 ('C.1.2','Parameters file code','Parameters file code',false,false),
	 ('C.1.4','Parameters check sum','Parameters check sum',false,false),
	 ('C.1.5','Firmware built date','Firmware built date',false,false),
	 ('C.1.6','Firmware check sum','Firmware check sum',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('C.6.0','Power down time counter','Power down time counter',false,false),
	 ('C.6.1','Battery remaining capacity','Battery remaining capacity',false,false),
	 ('F.F.0','Fatal error meter status','Fatal error meter status',false,false),
	 ('C.87.0','Active tariff','Active tariff',false,false),
	 ('0.2.1','Parameters scheme ID','Parameters scheme ID',false,false),
	 ('C.60.9','Fraud flag','Fraud flag',false,false),
	 ('0.3.0','Active energy meter constant','Active energy meter constant',false,false),
	 ('0.4.2','Current transformer ratio','Current transformer ratio',false,false),
	 ('0.4.3','Voltage transformer ratio','Voltage transformer ratio',false,false),
	 ('0.0.9','Identification number','Identification number',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('21.25','Active power phase L1','Instantaneous value of active power phase L1',false,false),
	 ('41.25','Active power phase L2','Instantaneous value of active power phase L2',false,false),
	 ('61.25','Active power phase L3','Instantaneous value of active power phase L3',false,false),
	 ('1.25','Total power','Instantaneous value of total power',false,false),
	 ('23.25','Reactive power phase L1','Instantaneous value of reactive power phase L1',false,false),
	 ('43.25','Reactive power phase L2','Instantaneous value of reactive power phase L2',false,false),
	 ('63.25','Reactive power phase L3','Instantaneous value of reactive power phase L3',false,false),
	 ('3.25','Reactive power phase total','Instantaneous value of reactive power phase total',false,false),
	 ('29.25','Apparent power phase L1','Instantaneous value of apparent power phase L1',false,false),
	 ('49.25','Apparent power phase L2','Instantaneous value of apparent power phase L2',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('69.25','Apparent power phase L3','Instantaneous value of apparent power phase L3',false,false),
	 ('C.3','State of the in/out control signals','State of the in/out control signals',false,false),
	 ('C.4','State of the internal control signals','State of the internal control signals',false,false),
	 ('C.5','Internal operating conditions','Internal operating conditions',false,false),
	 ('C.7.0','Total number of phase failures','Total number of phase failures',false,false),
	 ('C.51.4','DCF-77 last synchronization','DCF-77 last synchronization',false,false),
	 ('C.52.0','Phase information','Phase information',false,false),
	 ('81.7.0','Angle between U (L1) and U (L1)','Angle between U (L1) and U (L1)',false,false),
	 ('81.7.10','Angle between U (L1) and U (L2)','Angle between U (L1) and U (L2)',false,false),
	 ('81.7.20','Angle between U (L1) and U (L3)','Angle between U (L1) and U (L3)',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('81.7.4','Angle between I (L1) and I (L1)','Angle between I (L1) and I (L1)',false,false),
	 ('81.7.15','Angle between I (L2) and I (L2)','Angle between I (L2) and I (L2)',false,false),
	 ('81.7.26','Angle between I (L3) and I (L3)','Angle between I (L3) and I (L3)',false,false),
	 ('C.90.2','Unknown','Unknown',false,false),
	 ('32.7.0','Voltage phase L1','Instantaneous value of voltage phase L1',false,true),
	 ('52.7.0','Voltage phase L2','Instantaneous value of voltage phase L2',false,true),
	 ('72.7.0','Voltage phase L3','Instantaneous value of voltage phase L3',false,true),
	 ('32.25','Voltage phase L1','Instantaneous value of voltage phase L1',false,true),
	 ('52.25','Voltage phase L2','Instantaneous value of voltage phase L2',false,true),
	 ('72.25','Voltage phase L3','Instantaneous value of voltage phase L3',false,true);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('31.7.0','Current phase L1','Instantaneous value of current phase L1',true,false),
	 ('51.7.0','Current phase L2','Instantaneous value of current phase L2',true,false),
	 ('31.25','Current phase L1','Instantaneous value of current phase L1',true,false),
	 ('51.25','Current phase L2','Instantaneous value of current phase L2',true,false),
	 ('71.25','Current phase L3','Instantaneous value of current phase L3',true,false),
	 ('9.25','Total apparent power','Instantaneous value of total apparent power',false,false),
	 ('33.25','Power factor phase L1','Instantaneous value of power factor phase L1',false,false),
	 ('53.25','Power factor phase L2','Instantaneous value of power factor phase L2',false,false),
	 ('73.25','Power factor phase L3','Instantaneous value of power factor phase L3',false,false),
	 ('13.25','Average power factor','Instantaneous value of average power factor',false,false);
INSERT INTO meters.obis (obis,description_short,description_full,currentfactor,voltagefactor) VALUES
	 ('14.25','Frequency','Instantaneous value of frequency',false,false),
	 ('C.7.1','Phase failures phase 1','Number of phase failures phase 1',false,false),
	 ('C.7.2','Phase failures phase 2','Number of phase failures phase 2',false,false),
	 ('C.7.3','Phase failures phase 3','Number of phase failures phase 3',false,false),
	 ('71.7.0','Current phase L3','Instantaneous value of current phase L3',true,false);
