obis_codes = {
    "1.8.0": "Positive active energy (A+) total [kWh]",
    "1.8.1": "Positive active energy (A+) in tariff T1 [kWh]",
    "1.8.2": "Positive active energy (A+) in tariff T2 [kWh]",
    "1.8.3": "Positive active energy (A+) in tariff T3 [kWh]",
    "1.8.4": "Positive active energy (A+) in tariff T4 [kWh]",
    "2.8.0": "Negative active energy (A+) total [kWh]",
    "2.8.1": "Negative active energy (A+) in tariff T1 [kWh]",
    "2.8.2": "Negative active energy (A+) in tariff T2 [kWh]",
    "2.8.3": "Negative active energy (A+) in tariff T3 [kWh]",
    "2.8.4": "Negative active energy (A+) in tariff T4 [kWh]",
    "15.8.0": "Absolute active energy (A+) total [kWh]",
    "15.8.1": "Absolute active energy (A+) in tariff T1 [kWh]",
    "15.8.2": "Absolute active energy (A+) in tariff T2 [kWh]",
    "15.8.3": "Absolute active energy (A+) in tariff T3 [kWh]",
    "15.8.4": "Absolute active energy (A+) in tariff T4 [kWh]",
    "16.8.0": "Sum active energy without reverse blockade (A+ - A-) total [kWh]",
    "16.8.1": "Sum active energy without reverse blockade (A+ - A-) in tariff T1 [kWh]",
    "16.8.2": "Sum active energy without reverse blockade (A+ - A-) in tariff T2 [kWh]",
    "16.8.3": "Sum active energy without reverse blockade (A+ - A-) in tariff T3 [kWh]",
    "16.8.4": "Sum active energy without reverse blockade (A+ - A-) in tariff T4 [kWh]",
    "3.8.0": "Positive reactive energy (Q+) total [kvarh]",
    "3.8.1": "Positive reactive energy (Q+) in tariff T1 [kvarh]",
    "3.8.2": "Positive reactive energy (Q+) in tariff T2 [kvarh]",
    "3.8.3": "Positive reactive energy (Q+) in tariff T3 [kvarh]",
    "3.8.4": "Positive reactive energy (Q+) in tariff T4 [kvarh]",
    "4.8.0": "Negative reactive energy (Q-) total [kvarh]",
    "4.8.1": "Negative reactive energy (Q-) in tariff T1 [kvarh]",
    "4.8.2": "Negative reactive energy (Q-) in tariff T2 [kvarh]",
    "4.8.3": "Negative reactive energy (Q-) in tariff T3 [kvarh]",
    "4.8.4": "Negative reactive energy (Q-) in tariff T4 [kvarh]",
    "5.8.0": "Imported inductive reactive energy in 1-st quadrant (Q1) total [kvarh]",
    "5.8.1": "Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T1 [kvarh]",
    "5.8.2": "Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T2 [kvarh]",
    "5.8.3": "Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T3 [kvarh]",
    "5.8.4": "Imported inductive reactive energy in 1-st quadrant (Q1) in tariff T4 [kvarh]",
    "6.8.0": "Imported capacitive reactive energy in 2-nd quadrant (Q2) total [kvarh]",
    "6.8.1": "Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T1 [kvarh]",
    "6.8.2": "Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T2 [kvarh]",
    "6.8.3": "Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T3 [kvarh]",
    "6.8.4": "Imported capacitive reactive energy in 2-nd quadr. (Q2) in tariff T4 [kvarh]",
    "7.8.0": "Exported inductive reactive energy in 3-rd quadrant (Q3) total [kvarh]",
    "7.8.1": "Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T1 [kvarh]",
    "7.8.2": "Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T2 [kvarh]",
    "7.8.3": "Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T3 [kvarh]",
    "7.8.4": "Exported inductive reactive energy in 3-rd quadrant (Q3) in tariff T4 [kvarh]",
    "8.8.0": "Exported capacitive reactive energy in 4-th quadrant (Q4) total [kvarh]",
    "8.8.1": "Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T1 [kvarh]",
    "8.8.2": "Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T2 [kvarh]",
    "8.8.3": "Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T3 [kvarh]",
    "8.8.4": "Exported capacitive reactive energy in 4-th quadr. (Q4) in tariff T4 [kvarh]",
    "9.8.0": "Apparent energy (S+) total [kVAh]",
    "9.8.1": "Apparent energy (S+) in tariff T1 [kVAh]",
    "9.8.2": "Apparent energy (S+) in tariff T2 [kVAh]",
    "9.8.3": "Apparent energy (S+) in tariff T3 [kVAh]",
    "9.8.4": "Apparent energy (S+) in tariff T4 [kVAh]",
    "21.8.0": "Positive active energy (A+) in phase L1 total [kWh]",
    "41.8.0": "Positive active energy (A+) in phase L2 total [kWh]",
    "61.8.0": "Positive active energy (A+) in phase L3 total [kWh]",
    "22.8.0": "Negative active energy (A-) in phase L1 total [kWh]",
    "42.8.0": "Negative active energy (A-) in phase L2 total [kWh]",
    "62.8.0": "Negative active energy (A-) in phase L3 total [kWh]",
    "35.8.0": "Absolute active energy (|A|) in phase L1 total [kWh]",
    "55.8.0": "Absolute active energy (|A|) in phase L2 total [kWh]",
    "75.8.0": "Absolute active energy (|A|) in phase L3 total [kWh]",
    "1.6.0": "Positive active maximum demand (A+) total [kW]",
    "1.6.1": "Positive active maximum demand (A+) in tariff T1 [kW]",
    "1.6.2": "Positive active maximum demand (A+) in tariff T2 [kW]",
    "1.6.3": "Positive active maximum demand (A+) in tariff T3 [kW]",
    "1.6.4": "Positive active maximum demand (A+) in tariff T4 [kW]",
    "2.6.0": "Negative active maximum demand (A-) total [kW]",
    "2.6.1": "Negative active maximum demand (A-) in tariff T1 [kW]",
    "2.6.2": "Negative active maximum demand (A-) in tariff T2 [kW]",
    "2.6.3": "Negative active maximum demand (A-) in tariff T3 [kW]",
    "2.6.4": "Negative active maximum demand (A-) in tariff T4 [kW]",
    "15.6.0": "Absolute active maximum demand (|A|) total [kW]",
    "15.6.1": "Absolute active maximum demand (|A|) in tariff T1 [kW]",
    "15.6.2": "Absolute active maximum demand (|A|) in tariff T2 [kW]",
    "15.6.3": "Absolute active maximum demand (|A|) in tariff T3 [kW]",
    "15.6.4": "Absolute active maximum demand (|A|) in tariff T4 [kW]",
    "3.6.0": "Positive reactive maximum demand (Q+) total [kvar]",
    "4.6.0": "Negative reactive maximum demand (Q-) total [kvar]",
    "5.6.0": "Reactive maximum demand in Q1 (Q1) total [kvar]",
    "6.6.0": "Reactive maximum demand in Q2 (Q2) total [kvar]",
    "7.6.0": "Reactive maximum demand in Q3 (Q3) total [kvar]",
    "8.6.0": "Reactive maximum demand in Q4 (Q4) total [kvar]",
    "9.6.0": "Apparent maximum demand (S+) total [kVA]",
    "1.2.0": "Positive active cumulative maximum demand (A+) total [kW]",
    "1.2.1": "Positive active cumulative maximum demand (A+) in tariff T1 [kW]",
    "1.2.2": "Positive active cumulative maximum demand (A+) in tariff T2 [kW]",
    "1.2.3": "Positive active cumulative maximum demand (A+) in tariff T3 [kW]",
    "1.2.4": "Positive active cumulative maximum demand (A+) in tariff T4 [kW]",
    "2.2.0": "Negative active cumulative maximum demand (A-) total [kW]",
    "2.2.1": "Negative active cumulative maximum demand (A-) in tariff T1 [kW]",
    "2.2.2": "Negative active cumulative maximum demand (A-) in tariff T2 [kW]",
    "2.2.3": "Negative active cumulative maximum demand (A-) in tariff T3 [kW]",
    "2.2.4": "Negative active cumulative maximum demand (A-) in tariff T4 [kW]",
    "15.2.0": "Absolute active cumulative maximum demand (|A|) total [kW]",
    "15.2.1": "Absolute active cumulative maximum demand (|A|) in tariff T1 [kW]",
    "15.2.2": "Absolute active cumulative maximum demand (|A|) in tariff T2 [kW]",
    "15.2.3": "Absolute active cumulative maximum demand (|A|) in tariff T3 [kW]",
    "15.2.4": "Absolute active cumulative maximum demand (|A|) in tariff T4 [kW]",
    "3.2.0": "Positive reactive cumulative maximum demand (Q+) total [kvar]",
    "4.2.0": "Negative reactive cumulative maximum demand (Q-) total [kvar]",
    "5.2.0": "Reactive cumulative maximum demand in Q1 (Q1) total [kvar]",
    "6.2.0": "Reactive cumulative maximum demand in Q2 (Q2) total [kvar]",
    "7.2.0": "Reactive cumulative maximum demand in Q3 (Q3) total [kvar]",
    "8.2.0": "Reactive cumulative maximum demand in Q4 (Q4) total [kvar]",
    "9.2.0": "Apparent cumulative maximum demand (S+) total [kVA]",
    "1.4.0": "Positive active demand in a current demand period (A+) [kW]",
    "2.4.0": "Negative active demand in a current demand period (A-) [kW]",
    "15.4.0": "Absolute active demand in a current demand period (|A|) [kW]",
    "3.4.0": "Positive reactive demand in a current demand period (Q+) [kvar]",
    "4.4.0": "Negative reactive demand in a current demand period (Q-) [kvar]",
    "5.4.0": "Reactive demand in a current demand period in Q1 (Q1) [kvar]",
    "6.4.0": "Reactive demand in a current demand period in Q2 (Q2) [kvar]",
    "7.4.0": "Reactive demand in a current demand period in Q3 (Q3) [kvar]",
    "8.4.0": "Reactive demand in a current demand period in Q4 (Q4) [kvar]",
    "9.4.0": "Apparent demand in a current demand period (S+) [kVA]",
    "1.5.0": "Positive active demand in the last completed demand period (A+) [kW]",
    "2.5.0": "Negative active demand in the last completed demand period (A-) [kW]",
    "15.5.0": "Absolute active demand in the last completed demand period (|A|) [kW]",
    "3.5.0": "Positive reactive demand in the last completed demand period (Q+) [kvar]",
    "4.5.0": "Negative reactive demand in the last completed demand period (Q-) [kvar]",
    "5.5.0": "Reactive demand in the last completed demand period in Q1 (Q1) [kvar]",
    "6.5.0": "Reactive demand in the last completed demand period in Q2 (Q2) [kvar]",
    "7.5.0": "Reactive demand in the last completed demand period in Q3 (Q3) [kvar]",
    "8.5.0": "Reactive demand in the last completed demand period in Q4 (Q4) [kvar]",
    "9.5.0": "Apparent demand in the last completed demand period (S+) [kVA]",
    "1.7.0": "Positive active instantaneous power (A+) [kW]",
    "21.7.0": "Positive active instantaneous power (A+) in phase L1 [kW]",
    "41.7.0": "Positive active instantaneous power (A+) in phase L2 [kW]",
    "61.7.0": "Positive active instantaneous power (A+) in phase L3 [kW]",
    "2.7.0": "Negative active instantaneous power (A-) [kW]",
    "22.7.0": "Negative active instantaneous power (A-) in phase L1 [kW]",
    "42.7.0": "Negative active instantaneous power (A-) in phase L2 [kW]",
    "62.7.0": "Negative active instantaneous power (A-) in phase L3 [kW]",
    "15.7.0": "Absolute active instantaneous power (|A|) [kW]",
    "35.7.0": "Absolute active instantaneous power (|A|) in phase L1 [kW]",
    "55.7.0": "Absolute active instantaneous power (|A|) in phase L2 [kW]",
    "75.7.0": "Absolute active instantaneous power (|A|) in phase L3 [kW]",
    "16.7.0": "Sum active instantaneous power (A+ - A-) [kW]",
    "36.7.0": "Sum active instantaneous power (A+ - A-) in phase L1 [kW]",
    "56.7.0": "Sum active instantaneous power (A+ - A-) in phase L2 [kW]",
    "76.7.0": "Sum active instantaneous power (A+ - A-) in phase L3 [kW]",
    "3.7.0": "Positive reactive instantaneous power (Q+) [kvar]",
    "23.7.0": "Positive reactive instantaneous power (Q+) in phase L1 [kvar]",
    "43.7.0": "Positive reactive instantaneous power (Q+) in phase L2 [kvar]",
    "63.7.0": "Positive reactive instantaneous power (Q+) in phase L3 [kvar]",
    "4.7.0": "Negative reactive instantaneous power (Q-) [kvar]",
    "24.7.0": "Negative reactive instantaneous power (Q-) in phase L1 [kvar]",
    "44.7.0": "Negative reactive instantaneous power (Q-) in phase L2 [kvar]",
    "64.7.0": "Negative reactive instantaneous power (Q-) in phase L3 [kvar]",
    "9.7.0": "Apparent instantaneous power (S+) [kVA]",
    "29.7.0": "Apparent instantaneous power (S+) in phase L1 [kVA]",
    "49.7.0": "Apparent instantaneous power (S+) in phase L2 [kVA]",
    "69.7.0": "Apparent instantaneous power (S+) in phase L3 [kVA]",
    "11.7.0": "Instantaneous current (I) [A]",
    "31.7.0": "Instantaneous current (I) in phase L1 [A]",
    "51.7.0": "Instantaneous current (I) in phase L2 [A]",
    "71.7.0": "Instantaneous current (I) in phase L3 [A]",
    "91.7.0": "Instantaneous current (I) in neutral [A]",
    "11.6.0": "Maximum current (I max) [A]",
    "31.6.0": "Maximum current (I max) in phase L1 [A]",
    "51.6.0": "Maximum current (I max) in phase L2 [A]",
    "71.6.0": "Maximum current (I max) in phase L3 [A]",
    "91.6.0": "Maximum current (I max) in neutral [A]",
    "12.7.0": "Instantaneous voltage (U) [V]",
    "32.7.0": "Instantaneous voltage (U) in phase L1 [V]",
    "52.7.0": "Instantaneous voltage (U) in phase L2 [V]",
    "72.7.0": "Instantaneous voltage (U) in phase L3 [V]",
    "13.7.0": "Instantaneous power factor",
    "33.7.0": "Instantaneous power factor in phase L1",
    "53.7.0": "Instantaneous power factor in phase L2",
    "73.7.0": "Instantaneous power factor in phase L3",
    "14.7.0": "Frequency [Hz]",
    "C.53.1": "Tamper 1 energy register",
    "C.53.2": "Tamper 2 energy register",
    "C.53.3": "Tamper 3 energy register",
    "C.53.4": "Tamper 4 energy register",
    "C.53.11": "Tamper 5 energy register",
    "C.53.5": "Tamper 1 time counter register",
    "C.53.6": "Tamper 2 time counter register",
    "C.53.7": "Tamper 3 time counter register",
    "C.53.9": "Tamper 4 time counter register",
    "C.53.10": "Tamper 5 time counter register",
    "C.2.0": "Event parameters change - counter",
    "C.2.1": "Event parameters change - timestamp",
    "C.51.1": "Event terminal cover opened - counter",
    "C.51.2": "Event terminal cover opened - timestamp",
    "C.51.3": "Event main cover opened - counter",
    "C.51.5": "Event magnetic field detection start - counter",
    "C.51.6": "Event magnetic field detection start - timestamp",
    "C.51.7": "Event reverse power flow - counter",
    "C.51.8": "Event reverse power flow - timestamp",
    "C.7.10": "Event power down - timestamp",
    "C.51.13": "Event power up - counter",
    "C.51.14": "Event power up – timestamp",
    "C.51.15": "Event RTC (Real Time Clock) set - counter",
    "C.51.16": "Event RTC (Real Time Clock) set - timestamp",
    "C.51.21": "Event terminal cover closed - counter",
    "C.51.22": "Event terminal cover closed - timestamp",
    "C.51.23": "Event main cover closed - counter",
    "C.51.24": "Event main cover closed - timestamp",
    "C.51.25": "Event log-book 1 erased - counter",
    "C.51.26": "Event log-book 1 erased - timestamp",
    "C.51.27": "Event fraud start - counter",
    "C.51.28": "Event fraud start - timestamp",
    "C.51.29": "Event fraud stop - counter",
    "C.51.30": "Event fraud stop - timestamp",
    "0.9.1": "Current time (hh:mm:ss)",
    "0.9.2": "Date (YY.MM.DD or DD.MM.YY)",
    "0.9.4": "Date and Time (YYMMDDhhmmss)",
    "0.8.0": "Demand period [min]",
    "0.8.4": "Load profile period [min] (option)",
    "0.0.0": "Device address 1",
    "0.0.1": "Device address 2",
    "0.1.0": "MD reset counter",
    "0.1.2": "MD reset timestamp",
    "0.2.0": "Firmware version",
    "0.2.2": "Tariff program ID",
    "C.1.0": "Meter serial number",
    "C.1.2": "Parameters file code",
    "C.1.4": "Parameters check sum",
    "C.1.5": "Firmware built date",
    "C.1.6": "Firmware check sum",
    "C.6.0": "Power down time counter",
    "C.6.1": "Battery remaining capacity",
    "F.F.0": "Fatal error meter status",
    "C.87.0": "Active tariff",
    "0.2.1": "Parameters scheme ID",
    "C.60.9": "Fraud flag",
    "0.3.0": "Active energy meter constant",
    "0.4.2": "Current transformer ratio",
    "0.4.3": "Voltage transformer ratio",
    "0.0.9": "Identification number",
    "21.25": "Instantaneous value of active power phase L1",
    "41.25": "Instantaneous value of active power phase L2",
    "61.25": "Instantaneous value of active power phase L3",
    "1.25": "Instantaneous value of total power",
    "23.25": "Instantaneous value of reactive power phase L1",
    "43.25": "Instantaneous value of reactive power phase L2",
    "63.25": "Instantaneous value of reactive power phase L3",
    "3.25": "Instantaneous value of reactive power phase total",
    "29.25": "Instantaneous value of apparent power phase L1",
    "49.25": "Instantaneous value of apparent power phase L2",
    "69.25": "Instantaneous value of apparent power phase L3",
    "9.25": "Instantaneous value of total apparent power",
    "31.25": "Instantaneous value of current phase L1",
    "51.25": "Instantaneous value of current phase L2",
    "71.25": "Instantaneous value of current phase L3",
    "32.25": "Instantaneous value of voltage phase L1",
    "52.25": "Instantaneous value of voltage phase L2",
    "72.25": "Instantaneous value of voltage phase L3",
    "33.25": "Instantaneous value of power factor phase L1",
    "53.25": "Instantaneous value of power factor phase L2",
    "73.25": "Instantaneous value of power factor phase L3",
    "13.25": "Instantaneous value of average power factor",
    "14.25": "Instantaneous value of frequency",
    "C.3": "State of the in/out control signals",
    "C.4": "State of the internal control signals",
    "C.5": "Internal operating conditions",
    "C.7.0": "Total number of phase failures",
    "C.7.1": "Number of phase failures phase 1",
    "C.7.2": "Number of phase failures phase 2",
    "C.7.3": "Number of phase failures phase 3",
    "C.51.4": "DCF-77 last synchronization",
    "C.52.0": "Phase information",
    "C.86.0": "Installation check"
    }


obis_codes_short = {
    "1.8.0": "Positive active energy total",
    "1.8.1": "Positive active energy in tariff T1",
    "1.8.2": "Positive active energy in tariff T2",
    "1.8.3": "Positive active energy in tariff T3",
    "1.8.4": "Positive active energy in tariff T4",
    "2.8.0": "Negative active energy total",
    "2.8.1": "Negative active energy in tariff T1",
    "2.8.2": "Negative active energy in tariff T2",
    "2.8.3": "Negative active energy in tariff T3",
    "2.8.4": "Negative active energy in tariff T4",
    "15.8.0": "Absolute active energy total",
    "15.8.1": "Absolute active energy in tariff T1",
    "15.8.2": "Absolute active energy in tariff T2",
    "15.8.3": "Absolute active energy in tariff T3",
    "15.8.4": "Absolute active energy in tariff T4",
    "16.8.0": "Sum active energy without reverse blockade total",
    "16.8.1": "Sum active energy without reverse blockade in tariff T1",
    "16.8.2": "Sum active energy without reverse blockade in tariff T2",
    "16.8.3": "Sum active energy without reverse blockade in tariff T3",
    "16.8.4": "Sum active energy without reverse blockade in tariff T4",
    "3.8.0": "Positive reactive energy total",
    "3.8.1": "Positive reactive energy in tariff T1",
    "3.8.2": "Positive reactive energy in tariff T2",
    "3.8.3": "Positive reactive energy in tariff T3",
    "3.8.4": "Positive reactive energy in tariff T4",
    "4.8.0": "Negative reactive energy total",
    "4.8.1": "Negative reactive energy in tariff T1",
    "4.8.2": "Negative reactive energy in tariff T2",
    "4.8.3": "Negative reactive energy in tariff T3",
    "4.8.4": "Negative reactive energy in tariff T4",
    "5.8.0": "Imported inductive reactive energy in 1-st quadrant total",
    "5.8.1": "Imported inductive reactive energy in 1-st quadrant in tariff T1",
    "5.8.2": "Imported inductive reactive energy in 1-st quadrant in tariff T2",
    "5.8.3": "Imported inductive reactive energy in 1-st quadrant in tariff T3",
    "5.8.4": "Imported inductive reactive energy in 1-st quadrant in tariff T4",
    "6.8.0": "Imported capacitive reactive energy in 2-nd quadrant total",
    "6.8.1": "Imported capacitive reactive energy in 2-nd quadr. in tariff T1",
    "6.8.2": "Imported capacitive reactive energy in 2-nd quadr. in tariff T2",
    "6.8.3": "Imported capacitive reactive energy in 2-nd quadr. in tariff T3",
    "6.8.4": "Imported capacitive reactive energy in 2-nd quadr. in tariff T4",
    "7.8.0": "Exported inductive reactive energy in 3-rd quadrant total",
    "7.8.1": "Exported inductive reactive energy in 3-rd quadrant in tariff T1",
    "7.8.2": "Exported inductive reactive energy in 3-rd quadrant in tariff T2",
    "7.8.3": "Exported inductive reactive energy in 3-rd quadrant in tariff T3",
    "7.8.4": "Exported inductive reactive energy in 3-rd quadrant in tariff T4",
    "8.8.0": "Exported capacitive reactive energy in 4-th quadrant total",
    "8.8.1": "Exported capacitive reactive energy in 4-th quadr. in tariff T1",
    "8.8.2": "Exported capacitive reactive energy in 4-th quadr. in tariff T2",
    "8.8.3": "Exported capacitive reactive energy in 4-th quadr. in tariff T3",
    "8.8.4": "Exported capacitive reactive energy in 4-th quadr. in tariff T4",
    "9.8.0": "Apparent energy total",
    "9.8.1": "Apparent energy in tariff T1",
    "9.8.2": "Apparent energy in tariff T2",
    "9.8.3": "Apparent energy in tariff T3",
    "9.8.4": "Apparent energy in tariff T4",
    "21.8.0": "Positive active energy in phase L1 total",
    "41.8.0": "Positive active energy in phase L2 total",
    "61.8.0": "Positive active energy in phase L3 total",
    "22.8.0": "Negative active energy in phase L1 total",
    "42.8.0": "Negative active energy in phase L2 total",
    "62.8.0": "Negative active energy in phase L3 total",
    "35.8.0": "Absolute active energy in phase L1 total",
    "55.8.0": "Absolute active energy in phase L2 total",
    "75.8.0": "Absolute active energy in phase L3 total",
    "1.6.0": "Positive active maximum demand total",
    "1.6.1": "Positive active maximum demand in tariff T1",
    "1.6.2": "Positive active maximum demand in tariff T2",
    "1.6.3": "Positive active maximum demand in tariff T3",
    "1.6.4": "Positive active maximum demand in tariff T4",
    "2.6.0": "Negative active maximum demand total",
    "2.6.1": "Negative active maximum demand in tariff T1",
    "2.6.2": "Negative active maximum demand in tariff T2",
    "2.6.3": "Negative active maximum demand in tariff T3",
    "2.6.4": "Negative active maximum demand in tariff T4",
    "15.6.0": "Absolute active maximum demand total",
    "15.6.1": "Absolute active maximum demand in tariff T1",
    "15.6.2": "Absolute active maximum demand in tariff T2",
    "15.6.3": "Absolute active maximum demand in tariff T3",
    "15.6.4": "Absolute active maximum demand in tariff T4",
    "3.6.0": "Positive reactive maximum demand total",
    "4.6.0": "Negative reactive maximum demand total",
    "5.6.0": "Reactive maximum demand in Q1 total",
    "6.6.0": "Reactive maximum demand in Q2 total",
    "7.6.0": "Reactive maximum demand in Q3 total",
    "8.6.0": "Reactive maximum demand in Q4 total",
    "9.6.0": "Apparent maximum demand total",
    "1.2.0": "Positive active cumulative maximum demand total",
    "1.2.1": "Positive active cumulative maximum demand in tariff T1",
    "1.2.2": "Positive active cumulative maximum demand in tariff T2",
    "1.2.3": "Positive active cumulative maximum demand in tariff T3",
    "1.2.4": "Positive active cumulative maximum demand in tariff T4",
    "2.2.0": "Negative active cumulative maximum demand total",
    "2.2.1": "Negative active cumulative maximum demand in tariff T1",
    "2.2.2": "Negative active cumulative maximum demand in tariff T2",
    "2.2.3": "Negative active cumulative maximum demand in tariff T3",
    "2.2.4": "Negative active cumulative maximum demand in tariff T4",
    "15.2.0": "Absolute active cumulative maximum demand total",
    "15.2.1": "Absolute active cumulative maximum demand in tariff T1",
    "15.2.2": "Absolute active cumulative maximum demand in tariff T2",
    "15.2.3": "Absolute active cumulative maximum demand in tariff T3",
    "15.2.4": "Absolute active cumulative maximum demand in tariff T4",
    "3.2.0": "Positive reactive cumulative maximum demand total",
    "4.2.0": "Negative reactive cumulative maximum demand total",
    "5.2.0": "Reactive cumulative maximum demand in Q1 total",
    "6.2.0": "Reactive cumulative maximum demand in Q2 total",
    "7.2.0": "Reactive cumulative maximum demand in Q3 total",
    "8.2.0": "Reactive cumulative maximum demand in Q4 total",
    "9.2.0": "Apparent cumulative maximum demand total",
    "1.4.0": "Positive active demand in current demand period",
    "2.4.0": "Negative active demand in current demand period",
    "15.4.0": "Absolute active demand in current demand period",
    "3.4.0": "Positive reactive demand in current demand period",
    "4.4.0": "Negative reactive demand in current demand period",
    "5.4.0": "Reactive demand in current demand period in Q1",
    "6.4.0": "Reactive demand in current demand period in Q2",
    "7.4.0": "Reactive demand in current demand period in Q3",
    "8.4.0": "Reactive demand in current demand period in Q4",
    "9.4.0": "Apparent demand in current demand period",
    "1.5.0": "Positive active demand in the last completed demand period",
    "2.5.0": "Negative active demand in the last completed demand period",
    "15.5.0": "Absolute active demand in the last completed demand period",
    "3.5.0": "Positive reactive demand in the last completed demand period",
    "4.5.0": "Negative reactive demand in the last completed demand period",
    "5.5.0": "Reactive demand in the last completed demand period in Q1",
    "6.5.0": "Reactive demand in the last completed demand period in Q2",
    "7.5.0": "Reactive demand in the last completed demand period in Q3",
    "8.5.0": "Reactive demand in the last completed demand period in Q4",
    "9.5.0": "Apparent demand in the last completed demand period",
    "1.7.0": "Positive active instantaneous power",
    "21.7.0": "Positive active instantaneous power in phase L1",
    "41.7.0": "Positive active instantaneous power in phase L2",
    "61.7.0": "Positive active instantaneous power in phase L3",
    "2.7.0": "Negative active instantaneous power",
    "22.7.0": "Negative active instantaneous power in phase L1",
    "42.7.0": "Negative active instantaneous power in phase L2",
    "62.7.0": "Negative active instantaneous power in phase L3",
    "15.7.0": "Absolute active instantaneous power",
    "35.7.0": "Absolute active instantaneous power in phase L1",
    "55.7.0": "Absolute active instantaneous power in phase L2",
    "75.7.0": "Absolute active instantaneous power in phase L3",
    "16.7.0": "Sum active instantaneous power",
    "36.7.0": "Sum active instantaneous power in phase L1",
    "56.7.0": "Sum active instantaneous power in phase L2",
    "76.7.0": "Sum active instantaneous power in phase L3",
    "3.7.0": "Positive reactive instantaneous power",
    "23.7.0": "Positive reactive instantaneous power in phase L1",
    "43.7.0": "Positive reactive instantaneous power in phase L2",
    "63.7.0": "Positive reactive instantaneous power in phase L3",
    "4.7.0": "Negative reactive instantaneous power",
    "24.7.0": "Negative reactive instantaneous power in phase L1",
    "44.7.0": "Negative reactive instantaneous power in phase L2",
    "64.7.0": "Negative reactive instantaneous power in phase L3",
    "9.7.0": "Apparent instantaneous power",
    "29.7.0": "Apparent instantaneous power in phase L1",
    "49.7.0": "Apparent instantaneous power in phase L2",
    "69.7.0": "Apparent instantaneous power in phase L3",
    "11.7.0": "Instantaneous current",
    "31.7.0": "Instantaneous current in phase L1",
    "51.7.0": "Instantaneous current in phase L2",
    "71.7.0": "Instantaneous current in phase L3",
    "91.7.0": "Instantaneous current in neutral",
    "11.6.0": "Maximum current",
    "31.6.0": "Maximum current in phase L1",
    "51.6.0": "Maximum current in phase L2",
    "71.6.0": "Maximum current in phase L3",
    "91.6.0": "Maximum current in neutral",
    "12.7.0": "Instantaneous voltage",
    "32.7.0": "Instantaneous voltage in phase L1",
    "52.7.0": "Instantaneous voltage in phase L2",
    "72.7.0": "Instantaneous voltage in phase L3",
    "13.7.0": "Instantaneous power factor",
    "33.7.0": "Instantaneous power factor in phase L1",
    "53.7.0": "Instantaneous power factor in phase L2",
    "73.7.0": "Instantaneous power factor in phase L3",
    "14.7.0": "Frequency",
    "C.53.1": "Tamper 1 energy register",
    "C.53.2": "Tamper 2 energy register",
    "C.53.3": "Tamper 3 energy register",
    "C.53.4": "Tamper 4 energy register",
    "C.53.11": "Tamper 5 energy register",
    "C.53.5": "Tamper 1 time counter register",
    "C.53.6": "Tamper 2 time counter register",
    "C.53.7": "Tamper 3 time counter register",
    "C.53.9": "Tamper 4 time counter register",
    "C.53.10": "Tamper 5 time counter register",
    "C.2.0": "Event parameters change - counter",
    "C.2.1": "Event parameters change - timestamp",
    "C.51.1": "Event terminal cover opened - counter",
    "C.51.2": "Event terminal cover opened - timestamp",
    "C.51.3": "Event main cover opened - counter",
    "C.51.5": "Event magnetic field detection start - counter",
    "C.51.6": "Event magnetic field detection start - timestamp",
    "C.51.7": "Event reverse power flow - counter",
    "C.51.8": "Event reverse power flow - timestamp",
    "C.7.10": "Event power down - timestamp",
    "C.51.13": "Event power up - counter",
    "C.51.14": "Event power up – timestamp",
    "C.51.15": "Event RTC (Real Time Clock) set - counter",
    "C.51.16": "Event RTC (Real Time Clock) set - timestamp",
    "C.51.21": "Event terminal cover closed - counter",
    "C.51.22": "Event terminal cover closed - timestamp",
    "C.51.23": "Event main cover closed - counter",
    "C.51.24": "Event main cover closed - timestamp",
    "C.51.25": "Event log-book 1 erased - counter",
    "C.51.26": "Event log-book 1 erased - timestamp",
    "C.51.27": "Event fraud start - counter",
    "C.51.28": "Event fraud start - timestamp",
    "C.51.29": "Event fraud stop - counter",
    "C.51.30": "Event fraud stop - timestamp",
    "0.9.1": "Current time",
    "0.9.2": "Date",
    "0.9.4": "Date and Time",
    "0.8.0": "Demand period",
    "0.8.4": "Load profile period",
    "0.0.0": "Device address 1",
    "0.0.1": "Device address 2",
    "0.1.0": "MD reset counter",
    "0.1.2": "MD reset timestamp",
    "0.2.0": "Firmware version",
    "0.2.2": "Tariff program ID",
    "C.1.0": "Meter serial number",
    "C.1.2": "Parameters file code",
    "C.1.4": "Parameters check sum",
    "C.1.5": "Firmware built date",
    "C.1.6": "Firmware check sum",
    "C.6.0": "Power down time counter",
    "C.6.1": "Battery remaining capacity",
    "F.F.0": "Fatal error meter status",
    "C.87.0": "Active tariff",
    "0.2.1": "Parameters scheme ID",
    "C.60.9": "Fraud flag",
    "0.3.0": "Active energy meter constant",
    "0.4.2": "Current transformer ratio",
    "0.4.3": "Voltage transformer ratio",
    "0.0.9": "Identification number",
    "21.25": "Instantaneous value of active power phase L1",
    "41.25": "Instantaneous value of active power phase L2",
    "61.25": "Instantaneous value of active power phase L3",
    "1.25": "Instantaneous value of total power",
    "23.25": "Instantaneous value of reactive power phase L1",
    "43.25": "Instantaneous value of reactive power phase L2",
    "63.25": "Instantaneous value of reactive power phase L3",
    "3.25": "Instantaneous value of reactive power phase total",
    "29.25": "Instantaneous value of apparent power phase L1",
    "49.25": "Instantaneous value of apparent power phase L2",
    "69.25": "Instantaneous value of apparent power phase L3",
    "9.25": "Instantaneous value of total apparent power",
    "31.25": "Instantaneous value of current phase L1",
    "51.25": "Instantaneous value of current phase L2",
    "71.25": "Instantaneous value of current phase L3",
    "32.25": "Instantaneous value of voltage phase L1",
    "52.25": "Instantaneous value of voltage phase L2",
    "72.25": "Instantaneous value of voltage phase L3",
    "33.25": "Instantaneous value of power factor phase L1",
    "53.25": "Instantaneous value of power factor phase L2",
    "73.25": "Instantaneous value of power factor phase L3",
    "13.25": "Instantaneous value of average power factor",
    "14.25": "Instantaneous value of frequency",
    "C.3": "State of the in/out control signals",
    "C.4": "State of the internal control signals",
    "C.5": "Internal operating conditions",
    "C.7.0": "Total number of phase failures",
    "C.7.1": "Number of phase failures phase 1",
    "C.7.2": "Number of phase failures phase 2",
    "C.7.3": "Number of phase failures phase 3",
    "C.51.4": "DCF-77 last synchronization",
    "C.52.0": "Phase information",
    "C.86.0": "Installation check"
    }

table_obis_codes = {
    "1.5.0": "Positive active demand",
    "2.5.0": "Negative active demand",
    "5.5.0": "Reactive demand in Q1",
    "6.5.0": "Reactive demand in Q2",
    "7.5.0": "Reactive demand in Q3",
    "8.5.0": "Reactive demand in Q4",
    "0.9.1": "Current time",
    "0.9.2": "Date",
    "0.0.0": "Device address 1",
    "0.0.9": "Identification number",
    "21.25": "Active power phase L1",
    "41.25": "Active power phase L2",
    "61.25": "Active power phase L3",
    "1.25": "Total power",
    "23.25": "Reactive power phase L1",
    "43.25": "Reactive power phase L2",
    "63.25": "Reactive power phase L3",
    "3.25": "Reactive power phase total",
    "32.25": "Voltage phase L1",
    "52.25": "Voltage phase L2",
    "72.25": "Voltage phase L3",
    "33.25": "Power factor phase L1",
    "53.25": "Power factor phase L2",
    "73.25": "Power factor phase L3",
    "13.25": "Average power factor",
    "14.25": "Frequency",
    "C.3": "State of the in/out control signals",           # Not implemented
    "C.4": "State of the internal control signals",         # Not implemented
    "C.5": "Internal operating conditions",                 # Not implemented
    "C.7.0": "Total number of phase failures",
    "C.7.1": "Phase failures phase 1",
    "C.7.2": "Phase failures phase 2",
    "C.7.3": "Phase failures phase 3",
    "C.51.4": "DCF-77 last synchronization",                # Not implemented
    "C.52.0": "Phase information",                          # Not implemented
    "C.86.0": "Installation check"                          # Not implemented
    }

zabbix_obis_codes = {
    "1.5.0": "positiveActiveDemand",
    "2.5.0": "negativeActiveDemand",
    "5.5.0": "reactiveDemandQ1",
    "6.5.0": "reactiveDemandQ2",
    "7.5.0": "reactiveDemandQ3",
    "8.5.0": "reactiveDemandQ4",
    "bill-1.5.0": "Z-1-1.1.29.0",
    "bill-2.5.0": "Z-1-1.2.29.0",
    "bill-5.5.0": "Z-1-1.5.29.0",
    "bill-6.5.0": "Z-1-1.6.29.0",
    "bill-7.5.0": "Z-1-1.7.29.0",
    "bill-8.5.0": "Z-1-1.8.29.0",
    "bill-1.8.0": "Z-1-1.1.8.0-bill",
    "bill-2.8.0": "Z-1-1.2.8.0-bill",
    "bill-5.8.0": "Z-1-1.5.8.0-bill",
    "bill-6.8.0": "Z-1-1.6.8.0-bill",
    "bill-7.8.0": "Z-1-1.7.8.0-bill",
    "bill-8.8.0": "Z-1-1.8.8.0-bill",
    "bill-raw-1.5.0": "Z-1-1.1.29.0-raw",
    "bill-raw-2.5.0": "Z-1-1.2.29.0-raw",
    "bill-raw-5.5.0": "Z-1-1.5.29.0-raw",
    "bill-raw-6.5.0": "Z-1-1.6.29.0-raw",
    "bill-raw-7.5.0": "Z-1-1.7.29.0-raw",
    "bill-raw-8.5.0": "Z-1-1.8.29.0-raw",
    "bill-raw-1.8.0": "Z-1-1.1.8.0-bill-raw",
    "bill-raw-2.8.0": "Z-1-1.2.8.0-bill-raw",
    "bill-raw-5.8.0": "Z-1-1.5.8.0-bill-raw",
    "bill-raw-6.8.0": "Z-1-1.6.8.0-bill-raw",
    "bill-raw-7.8.0": "Z-1-1.7.8.0-bill-raw",
    "bill-raw-8.8.0": "Z-1-1.8.8.0-bill-raw",
    "bill-Log": "Z-1-1.Log",
    # "bill-1.5.0": "positiveActiveDemandBill",
    # "bill-2.5.0": "negativeActiveDemandBill",
    # "bill-5.5.0": "reactiveDemandQ1Bill",
    # "bill-6.5.0": "reactiveDemandQ2Bill",
    # "bill-7.5.0": "reactiveDemandQ3Bill",
    # "bill-8.5.0": "reactiveDemandQ4Bill",
    "0.9.1": "Current time",
    "0.9.2": "Date",
    "0.0.0": "Device address 1",
    "0.0.9": "Identification number",
    "21.25": "activePowerPhaseL1",
    "41.25": "activePowerPhaseL2",
    "61.25": "activePowerPhaseL3",
    "1.25": "totalPower",
    "23.25": "reactivePowerPhaseL1",
    "43.25": "reactivePowerPhaseL2",
    "63.25": "reactivePowerPhaseL3",
    "3.25": "reactivePowerTotal",
    "32.25": "voltagePhaseL1",
    "52.25": "voltagePhaseL2",
    "72.25": "voltagePhaseL3",
    "33.25": "powerFactorPhaseL1",
    "53.25": "powerFactorPhaseL2",
    "73.25": "powerFactorPhaseL3",
    "13.25": "powerFactorAvg",
    "14.25": "Frequency",
    "C.3": "State of the in/out control signals",           # Not implemented
    "C.4": "State of the internal control signals",         # Not implemented
    "C.5": "Internal operating conditions",                 # Not implemented
    "C.7.0": "phaseFailuresTotal",
    "C.7.1": "phaseFailuresPhase1",
    "C.7.2": "phaseFailuresPhase2",
    "C.7.3": "phaseFailuresPhase3",
    "C.51.4": "DCF-77 last synchronization",                # Not implemented
    "C.52.0": "Phase information",                          # Not implemented
    "C.86.0": "Installation check",                          # Not implemented
    "29.25": "apparentPowerPhaseL1",
    "49.25": "apparentPowerPhaseL2",
    "69.25": "apparentPowerPhaseL3",
    "9.25": "apparentPowerTotal",
    "31.25": "currentPhaseL1",
    "51.25": "currentPhaseL2",
    "71.25": "currentPhaseL3",
    "cos_phi": "CosinusPhi",
    "tan_phi": "TangensPhi",
    "1.2.1": "Z-1-1.1.2.1",
    "1.2.2": "Z-1-1.1.2.2",
    "1.6.1": "Z-1-1.1.6.1",
    "1.6.2": "Z-1-1.1.6.2",
    "1.8.0": "Z-1-1.1.8.0",
    "1.8.1": "Z-1-1.1.8.1",
    "1.8.2": "Z-1-1.1.8.2",
    "2.2.1": "Z-1-1.2.2.1",
    "2.2.2": "Z-1-1.2.2.2",
    "2.6.1": "Z-1-1.2.6.1",
    "2.6.2": "Z-1-1.2.6.2",
    "2.8.0": "Z-1-1.2.8.0",
    "2.8.1": "Z-1-1.2.8.1",
    "2.8.2": "Z-1-1.2.8.2",
    "5.8.0": "Z-1-1.5.8.0",
    "5.8.1": "Z-1-1.5.8.1",
    "5.8.2": "Z-1-1.5.8.2",
    "6.8.0": "Z-1-1.6.8.0",
    "6.8.1": "Z-1-1.6.8.1",
    "6.8.2": "Z-1-1.6.8.2",
    "7.8.0": "Z-1-1.7.8.0",
    "7.8.1": "Z-1-1.7.8.1",
    "7.8.2": "Z-1-1.7.8.2",
    "8.8.0": "Z-1-1.8.8.0",
    "8.8.1": "Z-1-1.8.8.1",
    "8.8.2": "Z-1-1.8.8.2",
    "raw-1.2.1": "Z-1-1.1.2.1-raw",
    "raw-1.2.2": "Z-1-1.1.2.2-raw",
    "raw-1.6.1": "Z-1-1.1.6.1-raw",
    "raw-1.6.2": "Z-1-1.1.6.2-raw",
    "raw-1.8.0": "Z-1-1.1.8.0-raw",
    "raw-1.8.1": "Z-1-1.1.8.1-raw",
    "raw-1.8.2": "Z-1-1.1.8.2-raw",
    "raw-2.2.1": "Z-1-1.2.2.1-raw",
    "raw-2.2.2": "Z-1-1.2.2.2-raw",
    "raw-2.6.1": "Z-1-1.2.6.1-raw",
    "raw-2.6.2": "Z-1-1.2.6.2-raw",
    "raw-2.8.0": "Z-1-1.2.8.0-raw",
    "raw-2.8.1": "Z-1-1.2.8.1-raw",
    "raw-2.8.2": "Z-1-1.2.8.2-raw",
    "raw-5.8.0": "Z-1-1.5.8.0-raw",
    "raw-5.8.1": "Z-1-1.5.8.1-raw",
    "raw-5.8.2": "Z-1-1.5.8.2-raw",
    "raw-6.8.0": "Z-1-1.6.8.0-raw",
    "raw-6.8.1": "Z-1-1.6.8.1-raw",
    "raw-6.8.2": "Z-1-1.6.8.2-raw",
    "raw-7.8.0": "Z-1-1.7.8.0-raw",
    "raw-7.8.1": "Z-1-1.7.8.1-raw",
    "raw-7.8.2": "Z-1-1.7.8.2-raw",
    "raw-8.8.0": "Z-1-1.8.8.0-raw",
    "raw-8.8.1": "Z-1-1.8.8.1-raw",
    "raw-8.8.2": "Z-1-1.8.8.2-raw",
    "0.1.2": "Z-1-1.0.1.2",
    "1.6.1-time": "Z-1-1.1.6.1-time",
    "1.6.2-time": "Z-1-1.1.6.2-time",
    "2.6.1-time": "Z-1-1.2.6.1-time",
    "2.6.2-time": "Z-1-1.2.6.2-time",
    "P.200_Bit15": "Z-1-1.Bit15",
    "P.200_Bit14": "Z-1-1.Bit14",
    "P.200_Bit13": "Z-1-1.Bit13",
    "P.200_Bit12": "Z-1-1.Bit12",
    "P.200_Bit11": "Z-1-1.Bit11",
    "P.200_Bit10": "Z-1-1.Bit10",
    "P.200_Bit9": "Z-1-1.Bit9",
    "P.200_Bit8": "Z-1-1.Bit8",
    "P.200_Bit7": "Z-1-1.Bit7",
    "P.200_Bit6": "Z-1-1.Bit6",
    "P.200_Bit5": "Z-1-1.Bit5",
    "P.200_Bit4": "Z-1-1.Bit4",
    "P.200_Bit3": "Z-1-1.Bit3",
    "P.200_Bit2": "Z-1-1.Bit2",
    "P.200_Bit1": "Z-1-1.Bit1",
    "P.200_Bit0": "Z-1-1.Bit0",
    "2000": "Z-1-1.2000",
    "23A6": "Z-1-1.23A6",
    "234C": "Z-1-1.234C",
    "334C": "Z-1-1.334C",
    "234D": "Z-1-1.234D",
    "334D": "Z-1-1.334D",
    "234E": "Z-1-1.234E",
    "334E": "Z-1-1.334E",
    "0.9.1-value": "Z-1-1.0.9.1-value",
    "0.9.2-value": "Z-1-1.0.9.2-value",
    "0.9.1-trigger": "Z-1-1.0.9.1-trigger",
    "0.9.2-trigger": "Z-1-1.0.9.2-trigger"
}

transform_set = {
    "positiveActiveDemand": "totalFactor",
    "negativeActiveDemand": "totalFactor",
    "reactiveDemandQ1": "totalFactor",
    "reactiveDemandQ2": "totalFactor",
    "reactiveDemandQ3": "totalFactor",
    "reactiveDemandQ4": "totalFactor",
    # "positiveActiveDemandBill": "totalFactor",
    # "negativeActiveDemandBill": "totalFactor",
    # "reactiveDemandQ1Bill": "totalFactor",
    # "reactiveDemandQ2Bill": "totalFactor",
    # "reactiveDemandQ3Bill": "totalFactor",
    # "reactiveDemandQ4Bill": "totalFactor",
    "Z-1-1.1.29.0": "totalFactor",
    "Z-1-1.2.29.0": "totalFactor",
    "Z-1-1.5.29.0": "totalFactor",
    "Z-1-1.6.29.0": "totalFactor",
    "Z-1-1.7.29.0": "totalFactor",
    "Z-1-1.8.29.0": "totalFactor",
    "Z-1-1.1.29.0-raw": "None",
    "Z-1-1.2.29.0-raw": "None",
    "Z-1-1.5.29.0-raw": "None",
    "Z-1-1.6.29.0-raw": "None",
    "Z-1-1.7.29.0-raw": "None",
    "Z-1-1.8.29.0-raw": "None",
    "Z-1-1.Log": "None",
    "Current time": "None",
    "Date": "None",
    "Device address 1": "None",
    "Identification number": "",
    "activePowerPhaseL1": "totalFactor",
    "activePowerPhaseL2": "totalFactor",
    "activePowerPhaseL3": "totalFactor",
    "totalPower": "totalFactor",
    "reactivePowerPhaseL1": "totalFactor",
    "reactivePowerPhaseL2": "totalFactor",
    "reactivePowerPhaseL3": "totalFactor",
    "reactivePowerTotal": "totalFactor",
    "voltagePhaseL1": "voltageRatio",
    "voltagePhaseL2": "voltageRatio",
    "voltagePhaseL3": "voltageRatio",
    "powerFactorPhaseL1": "None",
    "powerFactorPhaseL2": "None",
    "powerFactorPhaseL3": "None",
    "powerFactorAvg": "None",
    "Frequency": "None",
    "phaseFailuresTotal": "None",
    "phaseFailuresPhase1": "None",
    "phaseFailuresPhase2": "None",
    "phaseFailuresPhase3": "None",
    "apparentPowerPhaseL1": "totalFactor",
    "apparentPowerPhaseL2": "totalFactor",
    "apparentPowerPhaseL3": "totalFactor",
    "apparentPowerTotal": "totalFactor",
    "currentPhaseL1": "currentRatio",
    "currentPhaseL2": "currentRatio",
    "currentPhaseL3": "currentRatio",
    "CosinusPhi": "None",
    "TangensPhi": "None",
    "Z-1-1.1.2.1": "totalFactor",
    "Z-1-1.1.2.2": "totalFactor",
    "Z-1-1.1.6.1": "totalFactor",
    "Z-1-1.1.6.2": "totalFactor",
    "Z-1-1.1.8.0": "totalFactor",
    "Z-1-1.1.8.1": "totalFactor",
    "Z-1-1.1.8.2": "totalFactor",
    "Z-1-1.2.2.1": "totalFactor",
    "Z-1-1.2.2.2": "totalFactor",
    "Z-1-1.2.6.1": "totalFactor",
    "Z-1-1.2.6.2": "totalFactor",
    "Z-1-1.2.8.0": "totalFactor",
    "Z-1-1.2.8.1": "totalFactor",
    "Z-1-1.2.8.2": "totalFactor",
    "Z-1-1.5.8.0": "totalFactor",
    "Z-1-1.5.8.1": "totalFactor",
    "Z-1-1.5.8.2": "totalFactor",
    "Z-1-1.6.8.0": "totalFactor",
    "Z-1-1.6.8.1": "totalFactor",
    "Z-1-1.6.8.2": "totalFactor",
    "Z-1-1.7.8.0": "totalFactor",
    "Z-1-1.7.8.1": "totalFactor",
    "Z-1-1.7.8.2": "totalFactor",
    "Z-1-1.8.8.0": "totalFactor",
    "Z-1-1.8.8.1": "totalFactor",
    "Z-1-1.8.8.2": "totalFactor",
    "Z-1-1.1.2.1-raw": "None",
    "Z-1-1.1.2.2-raw": "None",
    "Z-1-1.1.6.1-raw": "None",
    "Z-1-1.1.6.2-raw": "None",
    "Z-1-1.1.8.0-raw": "None",
    "Z-1-1.1.8.1-raw": "None",
    "Z-1-1.1.8.2-raw": "None",
    "Z-1-1.2.2.1-raw": "None",
    "Z-1-1.2.2.2-raw": "None",
    "Z-1-1.2.6.1-raw": "None",
    "Z-1-1.2.6.2-raw": "None",
    "Z-1-1.2.8.0-raw": "None",
    "Z-1-1.2.8.1-raw": "None",
    "Z-1-1.2.8.2-raw": "None",
    "Z-1-1.5.8.0-raw": "None",
    "Z-1-1.5.8.1-raw": "None",
    "Z-1-1.5.8.2-raw": "None",
    "Z-1-1.6.8.0-raw": "None",
    "Z-1-1.6.8.1-raw": "None",
    "Z-1-1.6.8.2-raw": "None",
    "Z-1-1.7.8.0-raw": "None",
    "Z-1-1.7.8.1-raw": "None",
    "Z-1-1.7.8.2-raw": "None",
    "Z-1-1.8.8.0-raw": "None",
    "Z-1-1.8.8.1-raw": "None",
    "Z-1-1.8.8.2-raw": "None",
    "Z-1-1.0.1.2": "None",
    "Z-1-1.1.6.1-time": "None",
    "Z-1-1.1.6.2-time": "None",
    "Z-1-1.2.6.1-time": "None",
    "Z-1-1.2.6.2-time": "None",
    "Z-1-1.Bit15": "None",
    "Z-1-1.Bit14": "None",
    "Z-1-1.Bit13": "None",
    "Z-1-1.Bit12": "None",
    "Z-1-1.Bit11": "None",
    "Z-1-1.Bit10": "None",
    "Z-1-1.Bit9": "None",
    "Z-1-1.Bit8": "None",
    "Z-1-1.Bit7": "None",
    "Z-1-1.Bit6": "None",
    "Z-1-1.Bit5": "None",
    "Z-1-1.Bit4": "None",
    "Z-1-1.Bit3": "None",
    "Z-1-1.Bit2": "None",
    "Z-1-1.Bit1": "None",
    "Z-1-1.Bit0": "None",
    "Z-1-1.2000": "None",
    "Z-1-1.23A6": "None",
    "Z-1-1.234C": "None",
    "Z-1-1.334C": "None",
    "Z-1-1.234D": "None",
    "Z-1-1.334D": "None",
    "Z-1-1.234E": "None",
    "Z-1-1.334E": "None",
    "Z-1-1.0.9.1-value": "None",
    "Z-1-1.0.9.2-value": "None",
    "Z-1-1.0.9.1-trigger": "None",
    "Z-1-1.0.9.2-trigger": "None",
    "Z-1-1.1.8.0-bill": "totalFactor",
    "Z-1-1.2.8.0-bill": "totalFactor",
    "Z-1-1.5.8.0-bill": "totalFactor",
    "Z-1-1.6.8.0-bill": "totalFactor",
    "Z-1-1.7.8.0-bill": "totalFactor",
    "Z-1-1.8.8.0-bill": "totalFactor",
    "Z-1-1.1.8.0-bill-raw": "None",
    "Z-1-1.2.8.0-bill-raw": "None",
    "Z-1-1.5.8.0-bill-raw": "None",
    "Z-1-1.6.8.0-bill-raw": "None",
    "Z-1-1.7.8.0-bill-raw": "None",
    "Z-1-1.8.8.0-bill-raw": "None"
}